pod:
  name: peer0-org1-cli
  group: hlf
  replicaCount: 1
  volumes:
    - name: cli-claim1
      path: /Users/mauro/stigma/hlf-external/chaincode
      mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
    - name: cli-claim2
      path: /Users/mauro/stigma/hlf-external/channel-artifacts
      mountPath:  /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/channel-artifacts
    - name: cli-claim3
      path: /Users/mauro/stigma/hlf-external/crypto-config
      mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/

  container:
    image: hyperledger/fabric-tools:amd64-2.1.0
    workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    env:
      - name: FABRIC_LOGGING_SPEC
        value: INFO
      - name: CORE_PEER_ADDRESS
        value: peer0-org1:7051
      - name: CORE_PEER_ID
        value: cli-org1
      - name: CORE_PEER_LOCALMSPID
        value: org1MSP
      - name: CORE_PEER_MSPCONFIGPATH
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/users/Admin@org1/msp
      - name: CORE_PEER_TLS_CERT_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0-org1/tls/server.crt
      - name: CORE_PEER_TLS_ENABLED
        value: "true"
      - name: CORE_PEER_TLS_KEY_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0-org1/tls/server.key
      - name: CORE_PEER_TLS_ROOTCERT_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0-org1/tls/ca.crt
      - name: GOPATH
        value: /opt/gopath
      - name: ORDERER_CA
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/consortium/orderers/orderer0/msp/tlscacerts/tlsca.consortium-cert.pem
