app:
  name: peer0-org1
  group: hlf
  replicaCount: 1
  volumes:
    - name: dockersock
      path: /var/run
      mountPath: /host/var/run/
    - name: peer0-org1-claim1
      path: /Users/mauro/stigma/hlf-external/crypto-config/peerOrganizations/org1/peers/peer0-org1/msp
      mountPath: /etc/hyperledger/fabric/msp
    - name: peer0-org1-claim2
      path: /Users/mauro/stigma/hlf-external/crypto-config/peerOrganizations/org1/peers/peer0-org1/tls
      mountPath:  /etc/hyperledger/fabric/tls
    - name: peer0-persistentdata
      path: /Users/mauro/stigma/hlf-external/storage/peer0-org1
      mountPath: /var/hyperledger/production

  container:
    image: hyperledger/fabric-peer:amd64-2.1.0
    args: ["peer", "node", "start"]
    port: 7051
    env:
      - name: FABRIC_LOGGING_SPEC
        value: INFO
      - name: CORE_PEER_ADDRESS
        value: peer0-org1:7051
      - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
        value: peer0-org1:7051
      # - name: CORE_PEER_CHAINCODELISTENADDRESS
      #   value: localhost:7052
      - name: CORE_PEER_GOSSIP_USELEADERELECTION
        value: "true"
      - name: CORE_PEER_GOSSIP_BOOTSTRAP
        value: peer0-org1:7051
      - name: CORE_PEER_ID
        value: peer0-org1
      - name: CORE_PEER_LOCALMSPID
        value: org1MSP
      - name: CORE_PEER_PROFILE_ENABLED
        value: "true"
      - name: CORE_PEER_TLS_CERT_FILE
        value: /etc/hyperledger/fabric/tls/server.crt
      - name: CORE_PEER_TLS_ENABLED
        value: "true"
      - name: CORE_PEER_TLS_KEY_FILE
        value: /etc/hyperledger/fabric/tls/server.key
      - name: CORE_PEER_TLS_ROOTCERT_FILE
        value: /etc/hyperledger/fabric/tls/ca.crt
      # - name: CORE_VM_ENDPOINT
      #   value: http://localhost:2375
      - name: CORE_OPERATIONS_LISTENADDRESS
        value: 0.0.0.0:9443
      - name: CORE_METRICS_PROVIDER
        value: prometheus
      #hack
      # - name: CORE_PEER_CHAINCODELISTENADDRESS
      #   value: 0.0.0.0:7052
      - name: CORE_VM_ENDPOINT
        value: unix:///host/var/run/docker.sock
      - name: CORE_PEER_ADDRESSAUTODETECT
        value: "true"
  service:
      type: ClusterIP
      port: 7051

