environments:
  development:
  production:

helmDefaults:
  atomic: true
  cleanupOnFail: true

templates:
  default: &default
    chart: charts/{{`{{ .Release.Name }}`}}
    missingFileHandler: Warn
    values:
    - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

releases:
  - name: todo-app
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: chaincode-rest-api
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml


  - name: orderer0
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: orderer1
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: orderer2
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: peer0-org1
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: peer0-org2
    chart: charts/app
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml


  - name: peer0-org1-cli
    chart: charts/pod
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: peer0-org2-cli
    chart: charts/pod
    missingFileHandler: Warn
    values:
      - environments/{{ .Environment.Name }}/values/{{`{{ .Release.Name }}`}}.yaml

  - name: ingress-backend
    <<: *default
    chart: stable/nginx-ingress
    version: 1.36.0

  - name: ingress
    <<: *default
