apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaincode-rest-api
  name: chaincode-rest-api
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
  - name: "chaincode-rest-api"
    port: 8080
    targetPort: 8080
  selector:
    app: chaincode-rest-api