apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - args:
        - sh
        - -c
        - cd /app && bin/setup && bin/rails start
        env:
        - name: RAILS_ENV
          value: development
        - name: SECRET_KEY_BASE
          value: xxxx
        image: docker.io/bitnami/rails:6-debian-10
        name: todo-app
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /app
            name: todo-app-claim0
        workingDir: /app
      restartPolicy: Always
      volumes:
        - name: todo-app-claim0
          hostPath:
            path: /Users/mauro/stigma/hlf-external/services/stimulus_reflex_todomvc
            type: Directory
