apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
  - name: "todo-app"
    port: 3000
    targetPort: 3000
  selector:
    app: todo-app